// Strings should be unique across reducers so namespace them with the reducer name

export const FETCHING_AVAILABLE_COMPILERS = 'compilers.FETCHING_AVAILABLE_COMPILERS';
export const AVAILABLE_COMPILERS_FETCHED = 'compilers.AVAILABLE_COMPILERS_FETCHED';
export const ERRORED_FETCHING_AVAILABLE_COMPILERS = 'compilers.ERRORED_FETCHING_AVAILABLE_COMPILERS';


export const FETCHING_SELECTED_COMPILERS_DETAILS = 'compilers.FETCHING_SELECTED_COMPILER_DETAILS';
export const SELECTED_COMPILERS_DETAILS_FETCHED = 'compilers.SELECTED_COMPILERS_DETAILS_FETCHED';
export const ERRORED_FETCHING_SELECTED_COMPILERS_DETAILS = 'compilers.ERRORED_FETCHING_SELECTED_COMPILERS_DETAILS';