// Strings should be unique across reducers so namespace them with the reducer name

export const FETCHING_LICENSED_COMPILERS = 'compilers.FETCHING_LICENSED_COMPILERS';
export const LICENSED_COMPILERS_FETCHED = 'compilers.LICENSED_COMPILERS_FETCHED';
export const ERRORED_FETCHING_LICENSED_COMPILERS = 'compilers.ERRORED_FETCHING_LICENSED_COMPILERS';

export const FETCHING_ADDED_COMPILER_DETAILS = 'compilers.FETCHING_ADDED_COMPILER_DETAILS';
export const ADDED_COMPILER_DETAILS_FETCHED = 'compilers.ADDED_COMPILER_DETAILS_FETCHED';
export const ERRORED_FETCHING_ADDED_COMPILER_DETAILS = 'compilers.ERRORED_FETCHING_ADDED_COMPILER_DETAILS';


export const FETCHING_ADDED_COMPILER_OPTIONS = 'compilers.FETCHING_ADDED_COMPILER_OPTIONS';
export const ADDED_COMPILER_OPTIONS_FETCHED = 'compilers.ADDED_COMPILER_OPTIONS_FETCHED';
export const ERRORED_FETCHING_ADDED_COMPILER_OPTIONS = 'compilers.ERRORED_FETCHING_ADDED_COMPILER_OPTIONS';