// e.g. const ADD_TODO = 'ADD_TODO'

export const LOADING_COMPILERSELECTFIELD = 'LOADING_COMPILERSELECTFIELD';
export const ERRORED_LOADING_COMPILERSELECTFIELD = 'ERRORED_LOADING_COMPILERSELECTFIELD';
export const SET_OPTIONS_COMPILERSELECTFIELD = 'SET_OPTIONS_COMPILERSELECTFIELD';


export const LOADING_LOGSTEXTFIELD = 'LOADING_LOGSTEXTFIELD';
export const ERRORED_LOADING_LOGSTEXTFIELD = 'ERRORED_LOADING_LOGSTEXTFIELD';
export const SET_LOGS_LOGSTEXTFIELD = 'SET_LOGS_LOGSTEXTFIELD';
export const CLEAR_LOGSTEXTFIELD = 'CLEAR_LOGSTEXTFIELD';
export const ADD_LOG_LOGSTEXTFIELD = 'ADD_LOG_LOGSTEXTFIELD';
