// Strings should be unique across reducers so namespace them with the reducer name

export const FETCHING_ADDED_COMPILER_USER_OPTIONS = 'compilers.FETCHING_ADDED_COMPILER_USER_OPTIONS';
export const ADDED_COMPILER_USER_OPTIONS_FETCHED = 'compilers.ADDED_COMPILER_USER_OPTIONS_FETCHED';
export const ERRORED_FETCHING_ADDED_COMPILER_USER_OPTIONS = 'compilers.ERRORED_FETCHING_ADDED_COMPILER_USER_OPTIONS';